/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_onzhou_sox4android_sox_NativeSox */

#ifndef _Included_com_onzhou_sox4android_sox_NativeSox
#define _Included_com_onzhou_sox4android_sox_NativeSox
#ifdef __cplusplus
extern "C" {
#endif


/*
 * Class:     com_onzhou_sox4android_sox_NativeSox
 * Method:    reverb
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_onzhou_sox4android_sox_NativeSox_reverb
        (JNIEnv *, jobject, jstring, jstring, jint, jint, jint, jint, jint);


/*
 * Class:     com_onzhou_sox4android_sox_NativeSox
 * Method:    reverbBuffer
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_com_onzhou_sox4android_sox_NativeSox_reverbBuffer
        (JNIEnv *, jobject, jbyteArray, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
