/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_onzhou_sox4android_sox_NativeSox */

#ifndef _Included_com_onzhou_sox4android_sox_NativeSox
#define _Included_com_onzhou_sox4android_sox_NativeSox
#ifdef __cplusplus
extern "C" {
#endif


JNIEXPORT void JNICALL init(JNIEnv *env, jobject obj);

JNIEXPORT void JNICALL release(JNIEnv *env, jobject obj);

JNIEXPORT void JNICALL setReverbParam(JNIEnv *env, jobject obj,jint reverbrance,
                                  jint hfDamping, jint roomScale,
                                  jint stereoDepth,
                                  jint preDelay,jint wetGain);

JNIEXPORT void JNICALL reverbWavFile(JNIEnv *env, jobject obj, jstring jinput,jstring joutput);

/**
 * 内存中转换由于NDK在23以上才支持fmemopen函数
 * 因此此方法暂时不可用
 */
JNIEXPORT jbyteArray JNICALL reverbPcmBuffer
        (JNIEnv *, jobject, jbyteArray, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
