/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_onzhou_sox4android_sox_NativeSox */

#ifndef _Included_com_onzhou_sox4android_sox_NativeSox
#define _Included_com_onzhou_sox4android_sox_NativeSox
#ifdef __cplusplus
extern "C" {
#endif


#include "audio_effect.h"

/*
 * Class:     com_onzhou_sox4android_sox_NativeSox
 * Method:    reverb
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_onzhou_sox4android_sox_NativeSox_reverb
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
